[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.10.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
